force-app/main/default/objects/Case/fields/ActiveDirectory_Username__c.field-meta.xml
<CustomField>
    <fullName>ActiveDirectory_Username__c</fullName>
    <label>ActiveDirectory Username</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>SubType</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3rd party agreement</fullName>
            </value>
            <value>
                <fullName>Account update</fullName>
            </value>
            <value>
                <fullName>Additionnal Debtor - Co-lessee</fullName>
            </value>
            <value>
                <fullName>Address change</fullName>
            </value>
            <value>
                <fullName>Arrangement</fullName>
            </value>
            <value>
                <fullName>Assigment</fullName>
            </value>
            <value>
                <fullName>Auto-reply</fullName>
            </value>
            <value>
                <fullName>Banking Information</fullName>
            </value>
            <value>
                <fullName>Banko/ proposal</fullName>
            </value>
            <value>
                <fullName>Bill Of Sale</fullName>
            </value>
            <value>
                <fullName>Broker / Vendor</fullName>
            </value>
            <value>
                <fullName>Broker request</fullName>
            </value>
            <value>
                <fullName>Buyout</fullName>
            </value>
            <value>
                <fullName>Buyout - Audit</fullName>
            </value>
            <value>
                <fullName>Cash application</fullName>
            </value>
            <value>
                <fullName>Change payment date</fullName>
            </value>
            <value>
                <fullName>Cheque received</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Claim Info</fullName>
            </value>
            <value>
                <fullName>Collection Letters - NOC</fullName>
            </value>
            <value>
                <fullName>Collection Letters</fullName>
            </value>
            <value>
                <fullName>Collection Agencies - Assignation</fullName>
            </value>
            <value>
                <fullName>Collection release</fullName>
            </value>
            <value>
                <fullName>Communication with broker</fullName>
            </value>
            <value>
                <fullName>Contract Copy</fullName>
            </value>
            <value>
                <fullName>Contract information</fullName>
            </value>
            <value>
                <fullName>Copy of POI</fullName>
            </value>
            <value>
                <fullName>Corporate merger</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Customer Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Number_Of_Case__c/fields/Hard_Stop__c.field-meta.xml
<CustomField>
    <fullName>Hard_Stop__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Hard Stop</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Manage_Number_Of_Case__c/fields/Number_Of_Pending_Case__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Pending_Case__c</fullName>
    <label>Number Of Pending Case</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
public class CaseTriggerHandler {
    
    static final String message_14 = 'message_14';
    static final String message_15 = 'message_15';
    static final String message_16 = 'message_16';
     static final String message_17 = 'message_17';
    
    public static void OnBefore(Case[] caseObjects, Map<Id, Case> oldObjectMap){
        
        String userLanguage = UserInfo.getLanguage();
        String errMsg, cId, cOwnerId, cStatus, cType;
        List<Case> Cases = new List<Case>();
        Case caseObject;
         Case oldObject;
        String cAcc, cCont;
        Map<String, Object> response;
        // Map<Id, Case> mapCase = new Map<Id, Case>([SELECT CaseNumber, Owner.Name from Case where Status = 'Pending' and id in:caseObjects]);
        
        try{    
            List<Case> caseList = new List<Case>();
            
            for(case c : caseObjects){
                
                caseObject = c;
                cOwnerId = userinfo.getUserId();
            }
             if( caseObject.status != 'Closed' || caseObject.status != 'New' || caseObject.status != 'Escalated'){
                
               // Case emailCase = new Case(Id = cId);
                caseList = [Select id from Case Where (Origin = 'Email' OR Origin = 'EIP') AND Status = 'Pending' AND OwnerId = :caseObject.OwnerId];
             }
                system.debug('oldObjectMap---'+oldObjectMap+ '   caseObject Id---'+caseObject);
                
                if (oldObjectMap!=null){
                        oldObject = oldObjectMap.get(caseObject.Id);
              
            system.debug('test cStatus---'+caseObject.Status+ '---- la precedenete est --- '+oldObject.Status);
            
            if( caseObject.status != 'Closed' || caseObject.status != 'New' || caseObject.status != 'Escalated'){ // Waiting for Customer  Waiting For Support
         /*   if( caseObject.status == 'Pending' || caseObject.status == 'On Hold' || caseObject.status == 'Resolved' 
               || caseObject.status == 'Waiting for Customer'  || caseObject.status == 'Waiting For Support'){*/
               
                system.debug('test case 222---'+caseList.size());
                
                           
                system.debug('Le case status de changement est ---'+caseObject.Status);
                
                // Check personnal queue and manage case status eccepte when communication is from or to customer
                
                Manage_Number_Of_Case__c numberOfCase = Manage_Number_Of_Case__c.getOrgDefaults();
                
            if((caseList.size() > numberOfCase.Number_Of_Pending_Case__c &&  numberOfCase.Hard_Stop__c == true)
                && ((caseObject.status != 'Pending' && oldObject.Status == caseObject.status)
                                            || (caseObject.status != 'Pending' && (oldObject.Status != 'Pending' ))           
                                           )){
                                               system.debug('Le case status de changement est 2---'+caseObject.status);
                                               if(oldObject.Status != 'Waiting For Costomer' && caseObject.status != 'Waiting For Support' && caseList.size() > 3){
                                                   
                                                   
                                                   for(case caseO : caseObjects){
                                                       system.debug('test case 25---'+caseList);
                                                       errMsg = MessageUtils.ErrorMessage(userLanguage, message_14);
                                                       caseO.addError(errMsg);
                                                   }
                                               }
                                           }
                else {
                    
             
                }  
            }
            else{
           
                Integer intValue = ControllingPicklist.getFieldDependencies('Case', 'Type', 'Sub_Type__c', caseObject.Sub_Type__c);    //= 0; // = PicklistValueCheck.getPicklistValues(field);

                
                if(caseObject.Type == null  || (caseObject.Sub_Type__c == null && intValue > 0)){
             
                    for(case caseO : caseObjects){
                        
                        errMsg = MessageUtils.ErrorMessage(userLanguage, message_15);
                        //errMsg = 'You can not Closed Case without Case Type';
                        caseO.addError(errMsg);
                    }             
                }                
              
            }
        }
            
            
        }catch(Exception ex){
            
            If (ex.getMessage() != null){
                system.debug('======='+ex.getMessage());
             
                caseObjects[0].addError(MessageUtils.ErrorMessage(userLanguage, message_16));
            }
        }
    }
    
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    public static void OnAfeterUpdate(Case[] caseObjects){
        String cOwnerId, cId, cAd;
         for(case c : caseObjects){
            cId = c.Id;
            cOwnerId = c.OwnerId;
             cAd = c.ActiveDirectory_Username__c;
            }
        List<Group> sys = [select id, Name from Group where id = :cOwnerId];
        
        if(sys.size() > 0){
            
          user u = [Select Id from user where EIP_Login_User__c =:cAd limit 1];
            
          Case cas = new Case(Id = cId, OwnerId = u.Id);
            
            upsert cas;
        }
        
    }
    
    
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    
  
}