force-app/main/default/objects/Case/fields/Buyout_Type__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Type__c</fullName>
    <label>Buyout Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contrat_InfoLease__c.field-meta.xml
<CustomField>
    <fullName>Contrat_InfoLease__c</fullName>
    <label>Contrat InfoLease</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustId__c.field-meta.xml
<CustomField>
    <fullName>CustId__c</fullName>
    <label>Contract Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Buyout__c.field-meta.xml
<CustomField>
    <fullName>Date_Buyout__c</fullName>
    <label>Buyout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/EIP_Exception__c.field-meta.xml
<CustomField>
    <fullName>EIP_Exception__c</fullName>
    <label>EIP Exception</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Langue_Communication__c.field-meta.xml
<CustomField>
    <fullName>Langue_Communication__c</fullName>
    <label>Langue Communication</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>Operation_Type__c</fullName>
    <label>Operation Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BUYOUT</fullName>
            </value>
            <value>
                <fullName>GP</fullName>
                <label>Grille de paiement</label>
            </value>
            <value>
                <fullName>MCC</fullName>
                <label>Modifications compte client</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>PREPAYH</fullName>
            </value>
            <value>
                <fullName>Régulières</fullName>
            </value>
            <value>
                <fullName>Renouvèlement</fullName>
            </value>
            <value>
                <fullName>Résiliation</fullName>
            </value>
            <value>
                <fullName>Tiers</fullName>
            </value>
            <value>
                <fullName>VOID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateNew_Case.cls
public with sharing class CreateNew_Case {
    
   /* 
    public  static String  CreateNewCase(String eipAccount, String contactId, String eipContact, String eipContractNumber, String eipCustId,  
                                         String BuyoutType, Date epiDateBuyout, String eipOperationType, String eipLangue, Date eipExpiryDate,String userId, String userEmail, String eipExceptionMsg) {
                                             
                                             String caseSubject, caseId, uId, uEmail;    
                                             
                                             system.debug('ceci est un test');
                                             
                                             try{
                                                 
                                                 RecordType myRT = [Select Id From RecordType where Name = 'Customer Service'];
                                                 system.debug('record type '+ myRT.Id);                
                                                 Group gp = [select Id, name, DeveloperName from Group where type = 'queue' and DeveloperName = 'SAC_Queue'];
                                                 system.debug('********** Le compte est ***********3 = '+eipAccount+ ' le contact est **** = '+contactId);
                                                 
                                                 Case thisCase = new Case(  AccountId = eipAccount
                                                                          , RecordTypeId = myRT.Id
                                                                          , Status = 'New'
                                                                          , Origin = 'EIP'
                                                                          , Subject = 'EIP Buyout Request'
                                                                          , Type = eipOperationType
                                                                          , OwnerId = gp.Id
                                                                          , ContactId = contactId
                                                                          , Contrat_InfoLease__c = eipContractNumber
                                                                          , CustId__c =  eipCustId
                                                                          , Langue_Communication__c = eipLangue
                                                                          , Date_Buyout__c = epiDateBuyout
                                                                          , Operation_Type__c = eipOperationType
                                                                          , EIP_Exception__c = eipExceptionMsg
                                                                          , Requested_By__c = userId
                                                                          , SuppliedEmail = userEmail
                                                                          , Buyout_Type__c = BuyoutType
                                                                          , Request_Type__c = eipOperationType
                                                                         
                                                                          
                                                                         );
                                                 
                                                 System.debug('un new case creer '+thisCase);
                                                 
                                                 upsert thisCase;
                                                 
                                                 System.debug('Le Id du new case creer '+thisCase.Id);
                                                 
                                                 caseId = thisCase.Id;
                                                 
                                                 if (caseId != null){
                                                     
                                                     caseSubject = eipOperationType+ '[ref:'+caseId +':ref]';
                                                                                                          
                                                     Case updatecase = new Case(Id = caseId, subject = caseSubject);
                                                     update updatecase;
                                                     
                                                 }
                                                 
                                                 else {
                                                     caseId = null;
                                                 }
                                             }catch(Exception ex){
                                                 
                                                 String err_Msg = ex.getMessage();
                                                 
                                             } 
                                             return caseId; // caseId 
                                         }
    
*/    
}