force-app/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
                <isActive>false</isActive>
                <label>Accounting</label>
            </value>
            <value>
                <fullName>Accounts_Receivable</fullName>
                <isActive>false</isActive>
                <label>Accounts Receivable</label>
            </value>
            <value>
                <fullName>Admin Support CCS</fullName>
                <isActive>false</isActive>
                <label>Admin Support CCS</label>
            </value>
            <value>
                <fullName>Collection</fullName>
                <isActive>false</isActive>
                <label>Collection</label>
            </value>
            <value>
                <fullName>Insurance</fullName>
                <isActive>false</isActive>
                <label>Insurance</label>
            </value>
            <value>
                <fullName>Insurance_Claims</fullName>
                <isActive>false</isActive>
                <label>Insurance Claims</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
                <isActive>false</isActive>
                <label>Marketing</label>
            </value>
            <value>
                <fullName>Providers_Account</fullName>
                <isActive>false</isActive>
                <label>Providers Account</label>
            </value>
            <value>
                <fullName>Quittance</fullName>
                <isActive>false</isActive>
                <label>Quittance</label>
            </value>
            <value>
                <fullName>Transfer</fullName>
                <isActive>false</isActive>
                <label>Transfer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Collection.recordType-meta.xml
<RecordType>
    <fullName>Collection</fullName>
    <active>false</active>
    <businessProcess>Internal</businessProcess>
    <description>Record Type specific for Origin Email to Collection Queue</description>
    <label>Collection</label>
</RecordType>

force-app/main/default/classes/Case_Creation_Test.cls
@isTest(SeeAllData=true)
public  class Case_Creation_Test {

    
    @isTest
  
    static void CaseCreation(){

        User myUser = TestUtils.userTestRecord();
        System.debug('le user '+myUser);
                                            
       //Account myAccount = accountTestRecord();
        Account myAccount = TestUtils.accountTestRecord_Email();
        
        Contact myContact = TestUtils.contactTestRecordNoEmail(myAccount.Id);
       
        
       // Historique__c myHist = HistoriqueTestRecord(myAccount.Id, myContact.Id, 'test@analystic.ca');
        
        Test.StartTest();
        
        system.debug('le contact name est '+myContact.Name+ ' Le compte est '+myAccount);
         String eipCase1 = TestUtils.TestCase((String)myAccount.Id, (String)myContact.Name, 'tUser');    
         String eipCase2 = TestUtils.TestCase((String)myAccount.Id, (String)myContact.Name, null);    
         CaseCustomResponse Cas1 = Case_Creation_WS.createCase(eipCase1);
         CaseCustomResponse Cas2 = Case_Creation_WS.createCase(eipCase2);
                 
        String h1 = getCId(Cas1);
        String h2 = getCId(Cas2);

        String em9 = SendBuyoutEmail.BuyoutEmail(h1);

        Case_Creation_WS.getCaseInformations(h1);
       
        Case c = new Case(Id = h2, status = 'Escalated'); //Type = 'Redirect To', Department__c = 'Collection');
        update c;
        
        Test.StopTest();
        // Verify results
        System.assert(myAccount.Id != null);
       // System.assertEquals('TestEmail', myAccount.Name);
        
    }

  
    
    static String getCId(CaseCustomResponse s){
        
        String hist = JSON.serialize(s).remove('\\');
        Map<String, Object> resp = (Map<String, Object>) JSON.deserializeUntyped(hist);
        
        String caseId = (String)resp.get('caseId'); 
        
        
        return caseId;
    }
    
    


    }